books_hub/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup')
]

books_hub/books_hub/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='index'),
    path('welcome/',views.WelcomePage.as_view(), name='welcome'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('notes/', include('notes.urls', namespace='notes')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books_hub/notes/urls.py
from django.contrib import admin
from . import views
from django.urls import path,include
from django.views.generic.base import TemplateView

app_name='notes'

urlpatterns = [
    path('notes_list/', views.NotesListView.as_view(), name='list'),
]

books_hub/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

books_hub/notes/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Notes(models.Model):
    branch = models.CharField(max_length = 50)
    year = models.CharField(max_length = 2)
    subject = models.CharField(max_length = 50)
    name = models.CharField(max_length = 100)
    files = models.FileField(upload_to='pdfs', null=True)

    def str(self) :
        return self.name

    class Meta :
        ordering = ('year', )
        verbose_name = 'Notes'
        verbose_name_plural = 'Notes'

books_hub/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','first_name','last_name','email','password1','password2')
        model = get_user_model()

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)

books_hub/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms
# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

books_hub/books_hub/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

class WelcomePage(TemplateView):
    template_name = 'welcome.html'

books_hub/notes/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Notes
from .filters import NotesFilter
# Create your views here.

class NotesListView(ListView) :
    model = Notes
    template_name = 'notes/list.html'

    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        context['filter'] = NotesFilter(self.request.GET, queryset = self.get_queryset())
        return context

books_hub/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class = "login">LOGIN</h1>
  <form method="post" class = "login1">
    {% csrf_token %}
    {{form.as_p}}
    <button type="Submit" class="sub">Login</button>
  </form>

</div>
{% endblock %}

books_hub/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}
<div class="container">
  <h1 class = "signup">Sign Up here</h1>
  <form method="post" class = "signup1">
    {% csrf_token %}
    {{form|bootstrap}}
    <button type="Submit" class="sub2">Sign Up</button>
  </form>

</div>
{% endblock %}

books_hub/notes/templates/notes/list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block content %}
<div>
    <form method="GET" class = "filter">
        {{filter.form|bootstrap}}
        <br>
        <button type="Submit" class="search">Search</button>
    </form>
    <ul style="list-style: none;">
        {% for notes in filter.qs %}
        <li class = "item"> 
            <button class = "but"><a class = "notes" href="{{ notes.files.url }}" download >{{ notes.name }}</a></button>   
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

books_hub/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel = "stylesheet" href = "{%static 'css/home8.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Sriracha&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Acme&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Lexend+Mega&display=swap" rel="stylesheet">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark mynav" style="background-color:rgba(0,0,0,0.5);" role="navigation" id="navbar">
      <div class="container-fluid">
        <a class="navbar-brand mynav logo" href="{% url 'index' %}">BooksHub</a>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li class="nav-item"> <a class="nav-link" href="{% url 'notes:list' %}">Notes</a> </li>
              <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a> </li>
            {% else %}
              <li class="nav-item"> <a class="nav-link" href="{% url 'index' %}">Home</a> </li>
              <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:login' %}">Login</a> </li>
              <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a> </li>
              <li class="nav-item"> <a class="nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
            {% endif %}
          </ul>
        </div>
    </nav>
      <div class="container">
      {% block content %}

      {% endblock %}
      </div>
  </body>
</html>

books_hub/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class = "sec">
  <h1 class = "online">Online BookStore</h1>
  <p class = 'platform'>A Platform where students can get access to all the study material for free</p>
  <button type="Submit" class="start"><a href="{% url 'accounts:signup' %}">Join for Free</a></button>
</section>
{% endblock %}

books_hub/templates/welcome.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div>
  <h1 class = "welcome">Welcome {{user.first_name}} to Books Hub!!</h1>
</div>
{% endblock %}